name: rw_barcode_reader
description: Bar Code Reader Plugin for RealWear HMT-1
version: 1.0.0
homepage: https://github.com/Skyggedans/rw_barcode_reader

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.rockwellits.rw_plugins.rw_barcode_reader
    pluginClass: RwBarcodeReaderPlugin
